# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: tflow

builds:
  - id: tflow
    main: ./cmd/tflow
    binary: tflow
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/rapsnx/tflow/internal/buildinfo.version={{ .Tag }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: tflow
    ids:
      - tflow
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: checksums.txt
  algorithm: sha256
